##### Copyright 2018 The TensorFlow Authors.

In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## **Introduction to Colab and Python**

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l01c01_introduction_to_colab_and_python.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l01c01_introduction_to_colab_and_python.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

このColabへようこそ。ここでは、Pythonプログラミング言語とコースの演習に使用する環境の概要を簡単に紹介します：Colab。

Colabは、Google Cloudを使用してブラウザーで実行されるPython開発環境です。

たとえば、「Hello World」を印刷するには、マウスを[]の上に置いて、左上の再生ボタンを押します。 または、shift-enterを押して実行します。

In [1]:
# Never mind this statement, for compatibility reasons
# from __future__ import absolute_import, division, print_function, unicode_literals

In [2]:
print("Hello World")

Hello World


## Functions, Conditionals, and Iteration
Python関数を作成して、ループから呼び出しましょう。

In [3]:
def HelloWorldXY(x, y):
  if (x < 10):
    print("Hello World, x was < 10")
  elif (x < 20):
    print("Hello World, x was >= 10 but < 20")
  else:
    print("Hello World, x was >= 20")
  return x + y

for i in range(8, 25, 5):  # i=8, 13, 18, 23 (start, stop, step)
  print("--- Now running with i: {}".format(i))
  r = HelloWorldXY(i,i)
  print("Result from HelloWorld: {}".format(r))

--- Now running with i: 8
Hello World, x was < 10
Result from HelloWorld: 16
--- Now running with i: 13
Hello World, x was >= 10 but < 20
Result from HelloWorld: 26
--- Now running with i: 18
Hello World, x was >= 10 but < 20
Result from HelloWorld: 36
--- Now running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 46


In [4]:
print(HelloWorldXY(1,2))

Hello World, x was < 10
3


簡単ですね。

0から2（排他的）で始まるループが必要な場合は、次のいずれかを実行できます。

In [5]:
print("Iterate over the items. `range(2)` is like a list [0,1].")
for i in range(2):
  print(i)

print("Iterate over an actual list.")
for i in [0,1]:
  print(i)

print("While works")
i = 0
while i < 2:
  print(i)
  i += 1

Iterate over the items. `range(2)` is like a list [0,1].
0
1
Iterate over an actual list.
0
1
While works
0
1


In [6]:
print("Python supports standard key words like continue and break")
while True:
  print("Entered while")
  break

Python supports standard key words like continue and break
Entered while


## Numpy and lists
Pythonには言語に組み込まれたリストがあります。
ただし、これにはnumpyというライブラリーを使用します。
Numpyは、機械学習を行うときに役立つ多くのサポート機能を提供します。

ここには、インポート文も表示されます。 このステートメントにより、numpyパッケージ全体が利用可能になり、省略された「np」構文を使用してこれらのシンボルにアクセスできます。

In [7]:
import numpy as np  # Make numpy available using np.

# Create a numpy array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [8]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [9]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int64'>


In [10]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.50582004 0.81773973 0.87860975]
 [0.60908603 0.82415796 0.49993937]
 [0.1624997  0.20391819 0.61743237]]


In [11]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists")


You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists


## Colab Specifics

Colabは、直接アクセスできる仮想マシンです。 VMの端末でコマンドを実行するには、行の前に感嘆符（！）を付けます。

In [12]:
print("\nDoing $ls on filesystem")
!ls -l
!pwd


Doing $ls on filesystem
total 4000
-rw-r--r--  1 hironsuz  YAHOO\Domain Users   13113 12  3 15:30 [JPN]l01c01_introduction_to_colab_and_python.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users   37215 12  2 18:37 [JPN]l02c01_celsius_to_fahrenheit.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users  186770 12  3 09:49 [JPN]l03c01_classifying_images_of_clothing.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users  186753 12  3 10:31 [JPN]l04c01_image_classification_with_cnns.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users  426961 12  3 11:43 [JPN]l05c01_dogs_vs_cats_without_augmentation.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users  249117 12  3 12:47 [JPN]l05c02_dogs_vs_cats_with_augmentation.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users   44298 12  3 11:43 foo.png
-rwxr-xr-x@ 1 hironsuz  YAHOO\Domain Users   13546 11 26 20:25 l01c01_introduction_to_colab_and_python.ipynb
-rwxr-xr-x@ 1 hironsuz  YAHOO\Domain Users   45830 12  3 15:19 l02c01_celsius_to_fahrenheit.ipynb
-rwxr-xr-x@ 1 hiro

In [13]:
print("Install numpy")  # Just for test, numpy is actually preinstalled in all Colab instances
!pip install numpy

Install numpy


**Exercise**
このテキストセルの下にコードセルを作成し、以下にコードを追加します。

* 現在のディレクトリ（pwd）のパスを一覧表示する
* /（cd）に移動し、コンテンツをリストします（ls -l）


In [14]:
!pwd
!cd /
!ls -l
print("Hello")

/Users/hironsuz/Documents/tensorflow/courses/udacity_intro_to_tensorflow_for_deep_learning
total 4000
-rw-r--r--  1 hironsuz  YAHOO\Domain Users   13113 12  3 15:30 [JPN]l01c01_introduction_to_colab_and_python.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users   37215 12  2 18:37 [JPN]l02c01_celsius_to_fahrenheit.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users  186770 12  3 09:49 [JPN]l03c01_classifying_images_of_clothing.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users  186753 12  3 10:31 [JPN]l04c01_image_classification_with_cnns.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users  426961 12  3 11:43 [JPN]l05c01_dogs_vs_cats_without_augmentation.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users  249117 12  3 12:47 [JPN]l05c02_dogs_vs_cats_with_augmentation.ipynb
-rw-r--r--  1 hironsuz  YAHOO\Domain Users   44298 12  3 11:43 foo.png
-rwxr-xr-x@ 1 hironsuz  YAHOO\Domain Users   13546 11 26 20:25 l01c01_introduction_to_colab_and_python.ipynb
-rwxr-xr-x@ 1 hironsuz  YAHOO\Domain Users   45830

このコースでのColabの使用はすべて完全に無料または無料です。 GPUを使用しても、毎日数時間は無料で使用できます。

**GPUを使用**
* コースの演習の多くは、GPUランタイムを使用することでより迅速に実行されます。ランタイムタイプの変更|ハードウェアアクセラレータ| GPU

**コラボに関する最後の言葉**
* 各セルを順番に実行し、必要に応じてセルを編集および再実行できます
* 時々、これは意図しない結果をもたらす可能性があります。たとえば、ディメンションを配列に追加してセルを複数回実行すると、その後のセルが機能しなくなる場合があります。問題が発生した場合は、環境をリセットしてください。
  * ランタイム->ランタイムの再起動... Pythonシェルをリセットします
  * ランタイム->すべてのランタイムを再起動... Colabイメージをリセットし、100％クリーンな環境に戻します
* 以下を実行して、Colabの出力をクリアすることもできます：編集->すべての出力をクリア
* このコースのコラボはGitHubからロードされます。コード/出力のコピーが必要な場合は、Googleドライブに保存します。ファイル->ドライブにコピーを保存...

**もっと詳しく知る**
* [here](https://www.youtube.com/watch?v=inN8seMm7UI&list=PLQY2H8rRoyvwLbzbnKJ59NkZvQAW9wLbx&index=3）#CodingTensorFlowのエピソードを確認し、YouTubeチャンネルに登録することを忘れないでください;)
